name: Delete GitHub Release
description: Deletes a GitHub release by tag name
inputs:
  name:
    description: Repository name
    required: true
  tag:
    description: The release tag to delete
    required: true
runs:
  using: composite
  steps:
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_CLIENT_ID }}
        private-key: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_KEY }}
        owner: FLECS-Technologies
        repositories: |
          flecs-webapp-dummy
          flecs-build-dummy
          flecs-public-dummy

    - run: |
        set -e

        REPO="FLECS-Technologies/flecs-${{ inputs.name }}"
        TAG="${{ inputs.tag }}"
        TOKEN="${{ steps.app-token.outputs.token }}"

        echo "Searching Release-ID for tag: $TAG in repository: $REPO"

        release_response=$(curl -s -H "Authorization: token $TOKEN" \
          "https://api.github.com/repos/$REPO/releases/tags/$TAG")

        release_id=$(echo "$release_response" | jq -r '.id')

        if [[ "$release_id" == "null" || -z "$release_id" ]]; then
          echo "No release found for $TAG"
        else
          echo "Delete release with ID $release_id"
          curl -s -X DELETE -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/releases/$release_id"
        fi

        echo "Delete Git-Tag: $TAG"
        curl -s -X DELETE -H "Authorization: token $TOKEN" \
          "https://api.github.com/repos/$REPO/git/refs/tags/$TAG" || echo "Could not delete tag"
      shell: bash
