name: Delete GitHub Release
description: Deletes a GitHub release by tag name
inputs:
  name:
    description: Repository name
    required: true
  tag:
    description: The release tag to delete
    required: true
  github_token:
    description: GitHub Token
    required: true
runs:
  using: composite
  steps:
    - run: |
      # ...
      shell: bash
