name: Get completed runs
description: Get completed runs from release yml
inputs:
  name:
    description: Repository name
    required: true
  github_token:
    description: GitHub Token
    required: true
outputs:
  runs_data:
    description: Rawdata of runs
    value: ${{ steps.get.outputs.data }}
runs:
  using: composite
  steps:
    - name: Get completed runs
      id: get
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/FLECS-Technologies/flecs-${{ inputs.name }}/actions/workflows/release.workflow.yml/runs?status=completed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Output data
      shell: bash
      run: |
        echo "runs_data=${{ steps.get.outputs.data }}" >> $GITHUB_OUTPUT
