name: Bump webapp to next version
description: Updates version in package.json and package-lock.json to next version

inputs:
  tag:
    description: Released version
    required: true
  target_dir:
    description: Directory where files are located
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -e

        TARGET_DIR="${{ inputs.target_dir }}"
        RAW_TAG="${{ inputs.tag }}"
        CLEAN_TAG="${RAW_TAG#v}"
        NEXT_VERSION="${CLEAN_TAG}-next"

        jq --arg new_version "$NEXT_VERSION" '.version = $new_version' \
            "$TARGET_DIR/package.json" > "$TARGET_DIR/package.tmp" && mv "$TARGET_DIR/package.tmp" "$TARGET_DIR/package.json"

        jq --arg new_version "$NEXT_VERSION" \
          '.version = $new_version | .packages[""].version = $new_version' \
          "$TARGET_DIR/package-lock.json" > "$TARGET_DIR/lock.tmp" && mv "$TARGET_DIR/lock.tmp" "$TARGET_DIR/package-lock.json"