name: Get Jobs of Run
description: Get all jobs of a specific run
inputs:
  run_id:
    description: Run id of specific job
    required: true
  name:
    description: Repository name
    required: true
  github_token:
    description: GitHub Token
    required: true
outputs:
  jobs_data:
    description: "Jobdaten als JSON"
    value: ${{ steps.get.outputs.jobs_data }}
runs:
  using: composite
  steps:
    - name: Get jobs
      id: get
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/FLECS-Technologies/flecs-${{ inputs.name }}/actions/runs/${{ inputs.run_id }}/jobs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Output jobs
      shell: bash
      run: |
        echo "jobs_data=${{ steps.get.outputs.data }}" >> $GITHUB_OUTPUT
