name: Check status of build job
on:
  workflow_call:
    inputs:
      name:
        description: Name of repository
        required: true
        type: string
      env_version:
        description: Version of current release
        required: true
        type: string
      gh_token:
        description: Token from previous workflow
        required: true
        type: string
jobs:
  wait_for_run_completion:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Polling for completed workflow run
        uses: ./.github/actions/polling
        with:
          name: ${{ inputs.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  delete_release_on_failure:
    needs: wait_for_run_completion
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/delete-release-on-fail
        with:
          name: ${{ inputs.name }}
          tag: ${{ inputs.env_version }}
          github_token: ${{ inputs.gh_token }}

  check_build:
    needs: wait_for_run_completion
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Get completed runs
        id: get_runs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/FLECS-Technologies/flecs-${{ inputs.name }}/actions/workflows/release.workflow.yml/runs?status=completed&per_page=1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get run ID
        uses: ./.github/actions/get-run-id
        id: get_run_id
        with:
          data: ${{ steps.get_runs.outputs.data }}

      - name: Set run_id
        run: echo "RUN_ID=${{ steps.get_run_id.outputs.run_id }}" >> $GITHUB_ENV

      - name: Set route for API call
        run: echo "ROUTE=GET /repos/FLECS-Technologies/flecs-${{ inputs.name }}/actions/runs/$RUN_ID/jobs" >> $GITHUB_ENV
        env:
          RUN_ID: ${{ env.RUN_ID }}

      - name: Get jobs of workflow run
        id: get_jobs
        uses: octokit/request-action@v2.x
        with:
          route: ${{ env.ROUTE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Status of build job
        uses: ./.github/actions/build-job-status
        with:
          jobs_data: ${{ steps.get_jobs.outputs.data }}