name: Inputs for new release versions
on:
  workflow_dispatch:
    inputs:
      core_version:
        description: New core version
        required: false
        type: string
      webapp_version:
        description: New webapp version
        required: false
        type: string
      console_version:
        description: New console version
        required: false
        type: string
      core_branch:
        description: Branch for new core version
        required: false
        type: string
        default: main
      webapp_branch:
        description: Branch for new webapp version
        required: false
        type: string
        default: main
      console_branch:
        description: Branch for new console version
        required: false
        type: string
        default: main
env:
  INPUT_CORE_VERSION: ${{ inputs.core_version }}
  INPUT_CORE_BRANCH: ${{ inputs.core_branch }}
  INPUT_WEBAPP_VERSION: ${{ inputs.webapp_version }}
  INPUT_WEBAPP_BRANCH: ${{ inputs.webapp_branch }}
  INPUT_CONSOLE_VERSION: ${{ inputs.console_version }}
  INPUT_CONSOLE_BRANCH: ${{ inputs.console_branch }}
  V3_PATTERN: '^v3\.[0-9]+\.[0-9]+-hedgehog$'
  V4_PATTERN: '^v4\.[0-9]+\.[0-9]+-snowhare$'
  CONSOLE_PATTERN: '^v3\.[0-9]+\.[0-9]+'
jobs:
    validate_inputs:
      runs-on: ubuntu-latest
      steps:
        - name: check core version with Regex
          run: |
            if [[ -n "${{ inputs.core_version }}" && ! ("${{ inputs.core_version }}" =~ $V3_PATTERN || "${{ inputs.core_version }}" =~ $V4_PATTERN) ]]; then
              echo "Error: Core version does not match a valid pattern" >&2
              exit 1
            fi
        - name: check webapp version with Regex
          run: |
            if [[ -n "${{ inputs.webapp_version }}" && ! ("${{ inputs.webapp_version }}" =~ $V3_PATTERN || "${{ inputs.webapp_version }}" =~ $V4_PATTERN) ]]; then
              echo "Error: Webapp version does not match a valid pattern" >&2
              exit 1
            fi
        - name: check console version with Regex
          run: |
            if [[ -n "${{ inputs.console_version }}" && ! ("${{ inputs.console_version }}" =~ $CONSOLE_PATTERN) ]]; then
              echo "Error: Console version does not match a valid pattern" >&2
              exit 1
            fi
    release_webapp:
      uses: FLECS-Technologies/flecs-webapp-dummy/.github/workflows/release_webapp.yml@main
      secrets: inherit
      with:
        env_webapp_version: ${{ env.INPUT_WEBAPP_VERSION }}
        env_webapp_branch: ${{ env.INPUT_WEBAPP_BRANCH }}
    release_core:
      uses: FLECS-Technologies/flecs-build-dummy/.github/workflows/release_build.yml
      secrets: inherit
      with:
        env_core_version: ${{ env.INPUT_CORE_VERSION }}
        env_core_branch: ${{ env.INPUT_CORE_BRANCH }}