name: Release new version
on:
  workflow_dispatch:
    inputs:
      core_version:
        description: New core version
        required: false
        type: string
      webapp_version:
        description: New webapp version
        required: false
        type: string
      core_branch:
        description: Branch for new core version
        required: false
        type: string
        default: main
      webapp_branch:
        description: Branch for new webapp version
        required: false
        type: string
        default: main
      test_should_fail:
        description: simulate failure of workflow
        required: false
        type: string
      test_should_timeout:
        description: simulation timeout of workflow
        required: false
        type: string
jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate Inputs
        uses: ./.github/actions/validate-versions
        with:
          core_version: ${{ inputs.core_version }}
          webapp_version: ${{ inputs.webapp_version }}

  generate_token:
    runs-on: ubuntu-latest
    outputs:
      app_token: ${{ steps.app-token.outputs.token }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_CLIENT_ID }}
          private-key: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_KEY  }}
          owner: FLECS-Technologies
          repositories: |
            flecs-webapp-dummy
            flecs-build-dummy
            flecs-public-dummy

  release_webapp:
    if: inputs.webapp_version != ''
    needs: [validate_inputs, generate_token]
    uses: FLECS-Technologies/flecs-release/.github/workflows/create_release.yml@main
    with:
      name: webapp-dummy
      env_version: ${{ inputs.webapp_version }}
      env_branch: ${{ inputs.webapp_branch }}
      should_fail: ${{ inputs.test_should_fail }}
      should_timeout: ${{ inputs.test_should_timeout }}
    secrets:
      app_id: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_CLIENT_ID }}
      private_key: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_KEY  }}

  check_build_webapp:
    if: inputs.webapp_version != ''
    needs: release_webapp
    uses: ./.github/workflows/check_build_job.yml
    with:
      name: webapp-dummy
      env_version: ${{ inputs.webapp_version }}

  release_build:
    if: inputs.core_version != ''
    needs: [validate_inputs, generate_token]
    uses: FLECS-Technologies/flecs-release/.github/workflows/create_release.yml@main
    with:
      name: build-dummy
      env_version: ${{ inputs.core_version }}
      env_branch: ${{ inputs.core_branch }}
      should_fail: ${{ inputs.test_should_fail }}
      should_timeout: ${{ inputs.test_should_timeout }}
    secrets:
      app_id: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_CLIENT_ID }}
      private_key: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_KEY  }}

  check_build_build:
    if: inputs.core_version != ''
    needs: release_build
    uses: ./.github/workflows/check_build_job.yml
    with:
      name: build-dummy
      env_version: ${{ inputs.core_version }}

  release_public:
    if: inputs.core_version != ''
    needs: [validate_inputs, generate_token, release_build, check_build_build]
    uses: FLECS-Technologies/flecs-release/.github/workflows/create_release.yml@main
    with:
      name: public-dummy
      env_version: ${{ inputs.core_version }}
      env_branch: ${{ inputs.core_branch }}
      should_fail: ${{ inputs.test_should_fail }}
      should_timeout: ${{ inputs.test_should_timeout }}
    secrets:
      app_id: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_CLIENT_ID }}
      private_key: ${{ secrets.FLECS_WORKFLOW_AUTOMATION_KEY  }}

  check_build_public:
    if: inputs.core_version != ''
    needs: [check_build_build, release_public]
    uses: ./.github/workflows/check_build_job.yml
    with:
      name: public-dummy
      env_version: ${{ inputs.core_version }}